name: BackgroundJobs QA

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - src/Pilgaard.BackgroundJobs/**
      - .github/workflows/qodana_scan.yml
      - qodana.yaml

  pull_request:
    branches: [master]
    paths:
      - src/Pilgaard.BackgroundJobs/**
      - .github/workflows/qodana_scan.yml
      - qodana.yaml

jobs:
  scan:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      with:
        args: --project-dir,src/Pilgaard.BackgroundJobs
