name: BackgroundJobs CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - src/Pilgaard.BackgroundJobs/**
      - tests/Pilgaard.BackgroundJobs.Tests/**
      - tests/ApiApprovalTests.cs
      - .github/workflows/BackgroundJobs_ci.yml
      - Directory.Build.props

  pull_request:
    branches: [master]
    paths:
      - src/Pilgaard.BackgroundJobs/**
      - tests/Pilgaard.BackgroundJobs.Tests/**
      - tests/ApiApprovalTests.cs
      - .github/workflows/BackgroundJobs_ci.yml
      - Directory.Build.props

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore NuGet packages
        run: |
          dotnet restore ./src/Pilgaard.BackgroundJobs/Pilgaard.BackgroundJobs.csproj &&
          dotnet restore ./tests/Pilgaard.BackgroundJobs.Tests/Pilgaard.BackgroundJobs.Tests.csproj

      - name: Build
        run: |
          dotnet build ./src/Pilgaard.BackgroundJobs/Pilgaard.BackgroundJobs.csproj --no-restore &&
          dotnet build ./tests/Pilgaard.BackgroundJobs.Tests/Pilgaard.BackgroundJobs.Tests.csproj --no-restore

      - name: Run Test
        run: dotnet test ./tests/Pilgaard.BackgroundJobs.Tests/Pilgaard.BackgroundJobs.Tests.csproj --no-build --no-restore
