name: GitHub Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            generate_release_notes: true
            fail_on_unmatched_files: true
            token: ${{ secrets.GITHUB_TOKEN }}
