name: RecurringJobs CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - src/Pilgaard.RecurringJobs/**
      - tests/Pilgaard.RecurringJobs.Tests/**
      - tests/ApiApprovalTests.cs
      - .github/workflows/recurringjobs_ci.yml
      - Directory.Build.props

  pull_request:
    branches: [master]
    paths:
      - src/Pilgaard.RecurringJobs/**
      - tests/Pilgaard.RecurringJobs.Tests/**
      - tests/ApiApprovalTests.cs
      - .github/workflows/recurringjobs_ci.yml
      - Directory.Build.props

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore NuGet packages
        run: |
          dotnet restore ./src/Pilgaard.RecurringJobs/Pilgaard.RecurringJobs.csproj &&
          dotnet restore ./tests/Pilgaard.RecurringJobs.Tests/Pilgaard.RecurringJobs.Tests.csproj

      - name: Build
        run: |
          dotnet restore ./src/Pilgaard.RecurringJobs/Pilgaard.RecurringJobs.csproj --no-restore &&
          dotnet restore ./tests/Pilgaard.RecurringJobs.Tests/Pilgaard.RecurringJobs.Tests.csproj --no-restore

      - name: Run Test
        run: dotnet test ./tests/Pilgaard.RecurringJobs.Tests/Pilgaard.RecurringJobs.Tests.csproj --no-build --no-restore
