name: ScheduledJobs CD

on:
  push:
    tags:
      - scheduledjobs-v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore NuGet packages
        run: dotnet restore ./src/Pilgaard.ScheduledJobs/Pilgaard.ScheduledJobs.csproj

      - name: Build
        run: dotnet build ./src/Pilgaard.ScheduledJobs/Pilgaard.ScheduledJobs.csproj -c Release --no-restore

      - name: Package Nugets
        run: dotnet pack ./src/Pilgaard.ScheduledJobs/Pilgaard.ScheduledJobs.csproj -c Release --no-build --no-restore --include-source

      - name: Push Nugets
        run: dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
